[build]
publish = "dist"
command = "pnpm run generate"

[build.environment]
NODE_VERSION = "20"
NUXT_PUBLIC_SIGNALING_SERVER_URL = "ws://111.231.0.12:3000"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
