[build]
publish = "dist"
command = "pnpm run generate"

[build.environment]
NODE_VERSION = "20"
NUXT_PUBLIC_SIGNALING_SERVER_URL = "wss://file.rengshuai.com"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
