packages: []

catalog: null

catalogs:
  backend:
    '@types/uuid': ^10.0.0
    uuid: ^11.1.0
    ws: ^8.18.2
  build:
    '@nuxt/devtools': ^2.5.0
    '@nuxt/eslint': ^1.4.1
    '@nuxt/kit': ^3.17.5
    '@nuxtjs/color-mode': ^3.5.2
    '@pinia/nuxt': ^0.11.1
    '@unocss/eslint-config': ^66.1.4
    '@unocss/nuxt': ^66.1.4
    '@vueuse/nuxt': ^13.3.0
    nuxt: ^3.17.5
    unocss: ^66.1.4
    unplugin: ^2.3.5
    vite: ^6.3.5

  dev:
    '@antfu/eslint-config': ^4.14.1
    eslint: ^9.28.0
    eslint-plugin-format: ^1.0.1
    typescript: ^5.8.3
    vue-tsc: ^2.2.10
  frontend:
    '@vueuse/core': ^13.3.0
    pinia: ^3.0.3
    vue: ^3.5.16
  icons:
    '@iconify-json/carbon': ^1.2.9
    '@iconify-json/simple-icons': ^1.2.38
    '@iconify-json/twemoji': ^1.2.2
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
