catalogMode: prefer

shellEmulator: true

trustPolicy: no-downgrade
packages: []

catalog:
  '@types/node': ^25.0.3

catalogs:
  backend:
    '@types/uuid': ^10.0.0
    uuid: ^13.0.0
    ws: ^8.18.3
  build:
    '@nuxt/devtools': ^3.1.1
    '@nuxt/eslint': ^1.12.1
    '@nuxt/kit': ^4.2.2
    '@nuxtjs/color-mode': ^4.0.0
    '@pinia/nuxt': ^0.11.3
    '@unocss/eslint-config': ^66.5.10
    '@unocss/nuxt': ^66.5.10
    '@vueuse/nuxt': ^14.1.0
    nuxt: ^4.2.2
    unocss: ^66.5.10
    unplugin: ^2.3.11
    vite: ^7.3.0
  dev:
    '@antfu/eslint-config': ^6.7.1
    eslint: ^9.39.2
    eslint-plugin-format: ^1.1.0
    typescript: ^5.9.3
    vue-tsc: ^3.2.0
  frontend:
    '@vueuse/core': ^14.1.0
    pinia: ^3.0.4
    vue: ^3.5.26
  icons:
    '@iconify-json/carbon': ^1.2.15
    '@iconify-json/simple-icons': ^1.2.63
    '@iconify-json/twemoji': ^1.2.5

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
